import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Elfete',
      email: 'elfete@gmail.com',
      password: bcrypt.hashSync('Test123.', 8),
      isAdmin: true,
    },
    {
      name: 'Test',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('Test123.', 8),
      isAdmin: false,
    },
  ],
    animals: [
      {
        name: 'Bear',
        category: 'Test',
        image: '/images/bear.jpg',
        price: 120,
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'test',
      },
      {
        name: 'Bear2',
        category: 'Test',
        image: '/images/bear.jpg',
        price: 120,
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'test',
      },
      {
        name: 'Bear3',
        category: 'Test',
        image: '/images/bear.jpg',
        price: 120,
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'test',
      },
      {
        name: 'Bear4',
        category: 'Test',
        image: '/images/bear.jpg',
        price: 120,
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'test',
      },
      {
        name: 'Bear5',
        category: 'Test',
        image: '/images/bear.jpg',
        price: 120,
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'test',
      },
      {
        name: 'Bear6',
        category: 'Test',
        image: '/images/bear.jpg',
        price: 120,
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'test',
      },
    ],
  };
  export default data;