export const ADOPT_CREATE_REQUEST = 'ADOPT_CREATE_REQUEST';
export const ADOPT_CREATE_SUCCESS = 'ADOPT_CREATE_SUCCESS';
export const ADOPT_CREATE_FAIL = 'ADOPT_CREATE_FAIL';
export const ADOPT_CREATE_RESET = 'ADOPT_CREATE_RESET';