export const ANIMAL_LIST_REQUEST = 'ANIMAL_LIST_REQUEST';
export const ANIMAL_LIST_SUCCESS = 'ANIMAL_LIST_SUCCESS';
export const ANIMAL_LIST_FAIL = 'ANIMAL_LIST_FAIL';
export const ANIMAL_DETAILS_REQUEST = 'ANIMAL_DETAILS_REQUEST';
export const ANIMAL_DETAILS_SUCCESS = 'ANIMAL_DETAILS_SUCCESS';
export const ANIMAL_DETAILS_FAIL = 'ANIMAL_DETAILS_FAIL';